version: "3"
services:
  web: &rails_base
    build:
      dockerfile: Dockerfile
      context: .
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      RAILS_ENV: profile
      RACK_ENV: profile
      DATABASE_URL: postgres://postgres:mysecretpassword@db:5432/postgres
      YARN_INTEGRITY_ENABLED: "false"
    volumes:
      - .:/usr/src/app
    command: bundle exec rails server -b 0.0.0.0 -p 3000
  jobs:
    ports: []
    <<: *rails_base
    command: rails jobs:work
  prometheus_exporter:
    ports:
      - "9394:9394"
    <<: *rails_base
    command: bundle exec prometheus_exporter -b 0.0.0.0
  db:
    image: postgres
    ports:
    - "5432:5432"
