version: "3"
services:
  web: &rails_base
    build:
      dockerfile: Dockerfile
      context: .
    ports:
      - "3000:3000"
      - "9394:9394"
    depends_on:
      - db
    environment:
      RAILS_ENV: ${RAILS_ENV:-development}
      DATABASE_URL: postgres://postgres:password@db:5432/postgres
      YARN_INTEGRITY_ENABLED: "false"
    volumes:
      - .:/usr/src/app
    command: /bin/bash -c "
        [ "$RAILS_ENV" == "local_production" ] && bundle exec rake assets:precompile;
        rm -f /tmp/server.pid
        && bundle exec prometheus_exporter -b 0.0.0.0
        & bundle exec rails server -b 0.0.0.0 -P /tmp/server.pid
      "
  jobs:
    ports: []
    <<: *rails_base
    command: rails jobs:work
  webpacker:
    ports: []
    <<: *rails_base
    command: ./bin/webpack-dev-server
  db:
    image: postgres:9.6-alpine
    ports:
    - "5432:5432"
    environment:
      POSTGRES_PASSWORD: password
    volumes:
    - ./tmp/postgres_data:/var/lib/postgresql/data
