version: "3"
services:
  prometheus:
    image: prom/prometheus:0.18.0
#    depends_on:
#      - web
    volumes:
      - ./prometheus_data:/etc/prometheus/
    #      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - '-config.file=/etc/prometheus/prometheus.yml'
    ports:
      - '9394:9090'
  grafana:
    image: grafana/grafana:3.0.0-beta7
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=pass
    depends_on:
      - prometheus
    ports:
      - "3030:3000"
  web: &rails_base
    build:
      dockerfile: Dockerfile
      context: .
    tty: true
    stdin_open: true
    ports:
      - "3000:3000"
    depends_on:
      - db
      - prometheus
    environment:
      RAILS_ENV: local_production
#      RAILS_ENV: development
      PROMETHEUS_EXPORTER_HOST: prometheus
      PROMETHEUS_EXPORTER_BIND: localhost
      PROMETHEUS_EXPORTER_PORT: 9090
      SEND_LOGS_TO_TIMBER: "false"
      DATABASE_URL: postgres://rails:password@db:5432/postgres
      YARN_INTEGRITY_ENABLED: "false"
    volumes:
      - .:/usr/src/app
    command: bundle exec rails server -b 0.0.0.0 -p 3000
  jobs:
    ports: []
    <<: *rails_base
    command: rails jobs:work
  webpacker:
    tty: true
    stdin_open: true
    ports: []
    <<: *rails_base
    command: ./bin/webpack-dev-server
  db:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: rails
      POSTGRES_PASSWORD: password
