version: "3"
services:
  web: &rails_base
    build:
      dockerfile: Dockerfile
      context: .
    tty: true
    stdin_open: true
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      RAILS_ENV: local_production
#      RAILS_ENV: development
      SEND_LOGS_TO_TIMBER: "false"
      DATABASE_URL: postgres://rails:password@db:5432/postgres
      YARN_INTEGRITY_ENABLED: "false"
    volumes:
      - .:/usr/src/app
    command: bundle exec rails server -b 0.0.0.0 -p 3000
  jobs:
    ports: []
    <<: *rails_base
    command: rails jobs:work
  webpacker:
    tty: true
    stdin_open: true
    ports: []
    <<: *rails_base
    command: ./bin/webpack-dev-server
  db:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: rails
      POSTGRES_PASSWORD: password
