version: '3.9'
services:
  dockerhost:
    image: qoomon/docker-host
    cap_add: ['NET_ADMIN', 'NET_RAW']
    restart: on-failure
  prometheus:
    depends_on: [dockerhost]
    image: prom/prometheus:0.20.0
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - '-config.file=/etc/prometheus/prometheus.yml'
    ports:
      - '9090:9090'
  grafana:
    image: grafana/grafana:8.5.6
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=pass
    depends_on:
      - prometheus
    ports:
      - '3030:3000'
