version: '1.29'
services:
  dockerhost:
    image: qoomon/docker-host
    container_name: dockerhost
    cap_add: [ 'NET_ADMIN', 'NET_RAW' ]
    mem_limit: 8M
    restart: on-failure
  prometheus:
    depends_on: [ dockerhost ]
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
        - '9090:9090'
    volumes:
        - ./prometheus.yml:/etc/prometheus/prometheus.yml
    command:
        - '-config.file=/etc/prometheus/prometheus.yml'
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    depends_on:
        - prometheus
    ports:
        - "3030:3000"
    environment:
        GF_SECURITY_ADMIN_PASSWORD: <%= ENV['GRAFANA_PASS'] %>
volumes:
  grafana-storage:

