
common: &default_settings
  license_key: <%=  ENV["NEW_RELIC_KEY"] %>
  app_name: dev_to
  distributed_tracing:
    enabled: true
  log_level: info


development:
  <<: *default_settings
  app_name: dev_to (Development)

test:
  <<: *default_settings
  # It doesn't make sense to report to New Relic from automated test runs.
  monitor_mode: false

staging:
  <<: *default_settings
  app_name: dev_to (Staging)

production:
  <<: *default_settings

local_production:
  <<: *default_settings
  app_name: dev_to (LP)
  monitor_mode: true
