---
# The authentication token for the application.
authentication: <%= ENV['SKYLIGHT_AUTHENTICATION'] %>
production:                                 # Rails environment
  env: <%= 'localproduction' %> # Skylight environment
